services:
  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

    env_file:
      - .env

  questcatalog:
    build:
      context: ./questcatalog
      dockerfile: Dockerfile
    ports:
      - "5002:5002"

    env_file:
      - .env

  questprocess:
    build:
      context: ./questprocess
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

    env_file:
      - .env